language: node_js
node_js:
  - lts/*
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master

notifications:
  email:
    recipients:
      - 1440629746@qq.com
      - zhengjr989@163.com
    on_success: always # default: change
    on_failure: always # default: always